[general]
import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]
[window]
decorations = "none"
opacity = 0.9
padding = {x = 5, y= 5 }

[scrolling]
history= 10000
multiplier=3
[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold   = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
size = 12.0

